config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users, :only => [ :show ]
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attending.rb
class Attending < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: :user_id
  has_many :attendings
  has_many :attendees, through: :attendings, source: :user

  scope :past, -> { where("time < ?", DateTime.now) }
  scope :upcoming, -> { where("time > ?", DateTime.now) }

  def pretty_time
    self.time.to_formatted_s(:short)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events
  has_many :attendings
  has_many :attended_events, through: :attendings, source: :event

  def f_name
    [self.first_name, self.last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event, notice: "Event successfully created"
    else
      render :new
    end
  end

  def show
  end

  def index
    @events = Event.all.order("created_at DESC")
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated"
    else
      render :new
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :location, :description, :date, :time)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private_methods

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |f| %>
  <%= f.label :title %></br>
  <%= f.text_field :title %></br></br>
  <%= f.label :location%></br>
  <%= f.text_field :location %></br></br>
  <%= f.label :description%></br>
  <%= f.text_area :description %></br></br>
  <%= f.label :time%></br>
  <%= f.datetime_select :time %></br></br>
  <%= f.submit%>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form" %>

app/views/events/index.html.erb
<h1>Events</h1>

<h2>Upcoming</h2>
  <% Event.upcoming.each do |e| %>
    <%= link_to e.title, event_path(e) %>
    </br>
  <% end %>

</br>

<h2>Past</h2>
  <% Event.past.each do |e| %>
    <%= link_to e.title, event_path(e) %>
    </br>
  <% end %>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= render "form" %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<% e = @event %>
<table>
  <tr>
    <td><strong>Host:</strong></td>
    <td><%= e.creator.f_name %></td>
  </tr>
  <tr>
    <td><strong>Location:</strong></td>
    <td><%= e.location %></td>
  </tr>
  <tr>
    <td><strong>Description:</strong></td>
    <td><%= e.description %></td>
  </tr>
  <tr>
    <td><strong>Start Time:</strong></td>
    <td><%= e.pretty_time %></td>
  </tr>
</table>

<h2>Attending</h2>

  <% @event.attendees.each do |a| %>
    <%= link_to a.f_name, user_path(a) %>
    </br>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventLite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav>
      <%= link_to 'Home', root_path %>
      <% if user_signed_in? %>
        <%= link_to 'NewEvent!', new_event_path %>
        <%= link_to 'Profile', user_path(current_user)%>
        <%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Login', new_user_session_path %>
        <%= link_to 'SignUp', new_user_registration_path %>
      <% end%>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>User Profile</h1>
<table>
  <tr>
    <td>Name:</td>
    <td><%= [@user.first_name, @user.last_name].join(' ') %></td>
  </tr>
  <tr>
    <td>Username:</td>
    <td><%= @user.username %></td>
  </tr>
  <tr>
    <td>Email:</td>
    <td><%= @user.email %></td>
  </tr>
</table>

<h2>Hosted Events</h2>
  <% @user.events.each do |e|%>
    <table>
      <tr>
        <td><strong>Title:</strong></td>
        <td><%= link_to e.title, event_path(e) %></td>
      </tr>
      <tr>
        <td><strong>Location:</strong></td>
        <td><%= e.location %></td>
      </tr>
      <tr>
        <td><strong>Description:</strong></td>
        <td><%= e.description %></td>
      </tr>
      <tr>
        <td><strong>Start Time:</strong></td>
        <td><%= e.time %></td>
      </tr>
    </table>
  <% end %>

<h2>Attending Events</h2>

  <h3>Upcoming</h3>
    <% @user.attended_events.upcoming.each do |e| %>
      <table>
      <tr>
        <td><strong>Title:</strong></td>
        <td><%= link_to e.title, event_path(e) %></td>
      </tr>
      <tr>
        <td><strong>Host:</strong></td>
        <td><%= e.creator.f_name %></td>
      </tr>
      <tr>
        <td><strong>Location:</strong></td>
        <td><%= e.location %></td>
      </tr>
      <tr>
        <td><strong>Description:</strong></td>
        <td><%= e.description %></td>
      </tr>
      <tr>
        <td><strong>Start Time:</strong></td>
        <td><%= e.pretty_time %></td>
      </tr>
    </table>
    <% end %>
  
  <h3>Past</h3>
    <% @user.attended_events.past.each do |e| %>
      <table>
      <tr>
        <td><strong>Title:</strong></td>
        <td><%= link_to e.title, event_path(e) %></td>
      </tr>
      <tr>
        <td><strong>Host:</strong></td>
        <td><%= e.creator.f_name %></td>
      </tr>
      <tr>
        <td><strong>Location:</strong></td>
        <td><%= e.location %></td>
      </tr>
      <tr>
        <td><strong>Description::</strong></td>
        <td><%= e.description %></td>
      </tr>
      <tr>
        <td><strong>Start Time:</strong></td>
        <td><%= e.pretty_time %></td>
      </tr>
    </table>
    <% end %>

</br>

<% if @user == current_user %>
  <%= link_to 'Edit Profile', edit_user_registration_path %>
<% end %></br>

<%= link_to 'Back', root_path %>